################################################################################
#
# DATANAME CTA - hillas event columns
#
# DESCRIPTION column definitions for Hillas-style reconstruction
#
# This is an include file - the extension must be defined before
# including this.
#
# CONTENT bintable definition
#
# CHANGES
#
################################################################################
ttype# = HIL_MSW       / Mean Scaled Width 
tform# = 1E
ttype# = HIL_MSW_ERR      / error on Mean Scaled Width 
tform# = 1E
ttype# = HIL_MSL       / Mean Scaled Length
tform# = 1E
ttype# = HIL_MSL_ERR   / error on Mean Scaled Length
tform# = 1E
