################################################################################
#
# DATANAME CTA - analysis header
#
# DESCRIPTION
# contains all information about the analysis that was run
#
# This is an include file - the extension must be defined before
# including this.
#
# CONTENT header keywords
#
# CHANGES
#
################################################################################


