---
name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        root:
          - "rootproject/root:latest"
          #- "rootproject/root:6.20.08-ubuntu20.04"
          #- "rootproject/root:6.24.06-arch"
          #- "rootproject/root:6.22.06-fedora33"
          #- "rootproject/root:6.22.08-centos7"
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.root }}

    steps:
      - uses: actions/checkout@v4

      - name: install libblas
        run: apt-get install -y libblas-dev

      - name: build
        run: |
          root-config --version
          export EVNDISPSYS=$(echo $GITHUB_WORKSPACE)
          export SOFASYS=${EVNDISPSYS}/sofa
          ./install_sofa.sh CI
          make config
          make -j 4 VTS
